// Generated by orca-internal/Automations/feature-tips-automation.
// Source: https://onorca.dev/whats-new/changelog.json
// Review copy before merging; the automation only drafts PRs for human approval.
export const MARKETING_FEATURE_TIPS = [
  {
    id: 'changelog-1-3-41',
    priority: 'new',
    eyebrow: 'New in 1.3.41',
    title: "See every agent's live status, right in the sidebar",
    description:
      'Each worktree card now lists its agents inline with a colored status dot -- yellow while working, green when done. Plus a full GitHub Projects view in Tasks, source-control commit/push/pull from the sidebar, custom IDE fonts, and more.',
    action: 'open-release-notes',
    ctaLabel: "See what's new",
    mediaUrl: 'https://onorca.dev/whats-new/agent-statuses.gif',
    releaseNotesUrl: 'https://onorca.dev/changelog/1-3-41'
  }
] as const
